# Generated by Django 5.1.6 on 2025-02-26 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paroquia',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
